# One of 'error', 'warn', 'info', 'verbose', debug', 'silly'
loglevel: 'debug'
port: 4000
# Set to true to also take action on rules triggered by retained messages at start up (enabling this can have unnwanted side effects)
retained: false
logpath: 'logs'
mqtt:
  # URL to MQTT broker
  url: 'mqtt://192.168.1.201'
  # Configuration passed to the MQTT library
  options:
    username: 'mqtt_username'
    password: 'mqtt_password'
email:
  service:
    host: 'smtp.gmail.com'
    port: 587
    secure: false
    auth:
      user: 'seys.stefaan@gmail.com'
      pass: 'lgsrmnagjbtbqvsv'
  from: 'seys.stefaan@gmail.com'
pushover:
  service:
    user: 'uat6vxs8tm27kbv7wahpet2rdwsp9q'
    token: 'aev1g3k2mncgw6mcfv3s6dvjn1ztme'
topics:
  - "knx/#"
  - "hass/#"
rewrites:
    - regex: '(knx)\/(status)\/(.*\D.*)\/(.*\D.*)\/(.*\D.*)'
      measurement: '{{T.3}}.{{T.4}}'
      timestamp: '{{M.ts}}'
      tags:
        label: '{{T.5}}'
        dstgad: '{{{M.dstgad}}}'
      fields:
        value: '{{M.val}}'
    - regex: 'test\/(.*)'
      measurement: '{{T.1}}'
      tags:
        label: 'label{{T.1}}{{M.label}}'
      fields:
        f: 'value{{{T.1}}}{{M.label}}'
test:
  - regex: '(knx)\/(status)\/(.*)\/(.*)\/(.*)'
