# Sets the log level for the debug logs that will be created in the `logpath`
# One of 'error', 'warn', 'info', 'verbose', debug', 'silly'
loglevel: 'silly'
# The location where the logs files will be stored. This can be relative or absolute.
# This should not be touched when running scripts4mqtt inside a docker container.
logpath: '../logs'
# Debug mode
# If enabled, the server console will output detailed logs
debug: true
# Enable logging to elastic search
es:
  enabled: false
  node: 'http://es.elastic.home'
# Enable the API and React client and set the port on which it will listen.
api:
  enabled: true
  port: 4000
# MQTT topics to monitor. Topics not matching will be ignored.
topics:
  - "#"
# Set to true to also take action on rules triggered by retained messages at start up (enabling this can have unnwanted side effects)
retained: false
# MQTT connection
mqtt:
  # URL to MQTT broker
  url: 'mqtt://192.168.1.11'
  # Options passed straight to the `mqtt` library
  options:
    username: 'mqtt_username'
    password: 'mqtt_password'
# Email connection. The config is passed straight to the "nodemailer" library
email:
  service:
    host: 'smtp.gmail.com'
    port: 587
    secure: false
    auth:
      user: 'youremail@gmail.com'
      pass: 'gmail_app_password'
  from: 'scripts4mqtt@mail.com'
# Pushover connection. Passed straight to the "pushover-notifications" library
pushover:
  service:
    user: 'user_id'
    token: 'token'


