TimeDateUpdate:
  name: TDU
  category: Stuff
  order: 0
  condition:
    - type: cron
      trigger: always
      'off': ''
      'on': 15 * * * *
  ontrue:
    - type: script
      script: 'write(''knx/write/15/1/0'', new Date().toString());'
    - type: script
      script: 'write(''knx/write/15/1/1'', new Date().toString());'
    - type: pushover
      delay: 0
      interval: 0
      title: __REPLACE__
      message: ''
      sound: pushover
      priority: 0
    - type: mqtt
      delay: 0
      interval: 0
      topic: __REPLACE__
      value: __REPLACE__
  pendingOption: never
  enabled: false
  description: The description asdfasdf
  itemName: a
  jos: TDU
Logbook:
  name: Logbook
  category: Stuff
  order: 1
  condition:
    - type: cron
      trigger: always
      'off': ''
      'on': '*/1 * * * *'
  ontrue:
    - type: logbook
      message: test to logbook123
  pendingOption: always
  enabled: false
DoorBell:
  name: Doorbell
  category: Other Stuff
  order: 0
  condition:
    - type: mqtt
      trigger: on_flip_true
      topic: knx/status/15/2/5
      jmespath: val
      value: '0x01'
    - type: mqtt
      trigger: 'no'
      topic: __REPLACE__
      operator: eq
      jmespath: val
      value: ''
    - type: and
      condition: []
  ontrue:
    - type: mqtt
      delay: '1000'
      interval: 0
      topic: __REPLACE__
      value: __REPLACE__
    - type: script
      delay: 0
      interval: 0
      script: |-
        let a = {};
        for (const a of []) {
          console.log('test');
        }
  pendingOption: always
  enabled: false
  description: deurbel
  onfalse:
    - type: pushover
      delay: 0
      interval: 0
      title: __REPLACE__
      message: ''
      sound: pushover
      priority: 0
    - type: script
      delay: 0
      interval: 0
      script: ''
  type: mqtt
  trigger: on_flip_true
  topic: knx/status/15/2/5
  jmespath: val
  value: '0x01'
5ac67717893b:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition:
    - type: cron
      trigger: always
      'on': '* * * * *'
      'off': '-'
  ontrue:
    - type: logbook
      delay: 0
      interval: '10000'
      message: ontrue of test
493235c8de28:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
