TimeDateUpdate:
  name: TDU
  category: New
  order: 0
  condition:
    - type: and
      condition:
        - type: mqtt
          trigger: 'no'
          topic: hass/status/ventilation/high
          operator: eq
          jmespath: val
          value: ''
        - type: alias
          trigger: 'no'
          alias: A
          operator: eq
          jmespath: val
          value: ''
  ontrue:
    - type: script
      script: 'write(''knx/write/15/1/1'', new Date().toString());'
      enabled: true
    - type: mqtt
      delay: 0
      interval: 0
      topic: __REPLACE__
      value: __REPLACE__
      enabled: true
    - type: logbook
      delay: 0
      interval: 0
      message: ''
      enabled: true
  pendingOption: never
  enabled: false
  description: The description asdfasdfasdfasdfasdfsf
  itemName: a
  jos: TDU
  onfalse:
    - type: script
      delay: 0
      enabled: true
      interval: 0
      script: ''
    - type: webhook
      delay: 0
      enabled: true
      interval: 0
      url: __REPLACE__
Logbook:
  name: Logbook
  category: Stuff
  order: 1
  condition:
    - type: or
      condition:
        - type: cron
          trigger: on_flip_true
          'off': '*/2 * * * *'
          'on': '*/1 * * * *'
    - type: mqtt
      trigger: always
      topic: test
      operator: eq
      jmespath: val
      value: '1'
  ontrue:
    - type: logbook
      message: 'test to logbook: {{M}} {{topic}} {{M.val}}'
      enabled: true
    - type: logbook
      delay: 0
      interval: 0
      message: Should not appear
      enabled: false
  pendingOption: always
  enabled: true
DoorBell:
  name: Temp1
  category: Nice stuuff
  order: 0
  condition:
    - type: mqtt
      trigger: always
      topic: knx/status/Verwarming/Actuele_temperatuur/Living
      operator: gt
      jmespath: val
      value: '24'
  ontrue:
    - type: logbook
      delay: 0
      interval: 0
      message: Hot
  enabled: true
  description: Safari
  onfalse:
    - type: logbook
      delay: 0
      interval: 0
      message: Cold
d25f8c914a65:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition:
    - type: mqtt
      trigger: 'no'
      topic: __REPLACE__
      operator: eq
      jmespath: val
      value: ''
  ontrue:
    - type: email
      delay: 0
      interval: 0
      to: __REPLACE__@mail.com
      subject: __REPLACE__
      body: ''
  onfalse:
    - type: webhook
      delay: 0
      interval: 0
      url: __REPLACE__
'78903448e823':
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
