TimeDateUpdate:
  name: Test
  category: Stuff
  order: 0
  condition:
    - type: cron
      trigger: always
      'off': ''
      'on': 15 * * * *
  ontrue:
    - type: script
      script: 'write(''knx/write/15/1/0'', new Date().toString());'
    - type: script
      script: 'write(''knx/write/15/1/1'', new Date().toString());'
  pendingOption: never
  enabled: false
  description: The description asdfasdf
  itemName: a
Logbook:
  name: Logbook
  category: Stuff
  order: 1
  condition:
    - type: cron
      trigger: always
      'off': ''
      'on': '*/1 * * * *'
  ontrue:
    - type: logbook
      message: test to logbook123
  pendingOption: always
  enabled: false
DoorBell:
  name: Doorbell
  category: Other Stuff
  order: 0
  condition:
    - type: mqtt
      trigger: on_flip_true
      topic: knx/status/15/2/3
      jmespath: val
      value: '0x01'
    - type: and
      condition: []
  ontrue:
    - type: pushover
      message: Notification from script4mqtt
      title: Doorbell ringing!
      sound: bike
      priority: 1
  pendingOption: always
  enabled: false
ef2a1abf4e20:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
2bf3c2a03716:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
b59d44f48aac:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
76b2870b34bc:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
23ddb5f2160f:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
6ba57721006b:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
fc9d8538d3be:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
0503a11f5bf2:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
e53befbbc30b:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
bb8ca3508efc:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
76e2546bae27:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
ff732b08296d:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
ead14ef7e089:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
a7555060f65c:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
61b8a52cec9c:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
8c19de6b776a:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
0afee6c5a58a:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
ea459e87573f:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
955541a9a0ae:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
