TimeDateUpdate:
  name: TDU
  category: New
  order: 0
  condition:
    - type: mqtt
      trigger: 'no'
      topic: hass/status/ventilation/high
      operator: eq
      jmespath: val
      value: ''
    - type: and
      condition:
        - type: alias
          trigger: 'no'
          alias: A
          operator: eq
          jmespath: val
          value: ''
        - type: alias
          trigger: 'no'
          alias: B
          operator: eq
          jmespath: val
          value: ''
        - type: alias
          trigger: on_flip
          alias: __REPLACE__
          operator: eq
          jmespath: val
          value: ''
          alias_: drty
        - type: cron
          trigger: always
          'off': ''
          'on': 15 * * * *
        - type: cron
          trigger: always
          'on': 0 0 * * *
          'off': '-'
  ontrue:
    - type: script
      script: 'write(''knx/write/15/1/0'', new Date().toString());'
    - type: script
      script: 'write(''knx/write/15/1/1'', new Date().toString());'
    - type: pushover
      delay: 0
      interval: 0
      title: __REPLACE__
      message: ''
      sound: pushover
      priority: 0
    - type: mqtt
      delay: 0
      interval: 0
      topic: __REPLACE__
      value: __REPLACE__
  pendingOption: never
  enabled: false
  description: The description asdfasdfasdfasdfasdfsf
  itemName: a
  jos: TDU
Logbook:
  name: Logbook
  category: Stuff
  order: 1
  condition:
    - type: cron
      trigger: on_flip_true
      'off': '*/2 * * * *'
      'on': '*/1 * * * *'
  ontrue:
    - type: logbook
      message: test to logbook123
  pendingOption: always
  enabled: true
DoorBell:
  name: Temp1
  category: Nice stuuff
  order: 0
  condition:
    - type: mqtt
      trigger: always
      topic: knx/status/Verwarming/Actuele_temperatuur/Living
      operator: gt
      jmespath: val
      value: '24'
  ontrue:
    - type: logbook
      delay: 0
      interval: 0
      message: Hot
  enabled: true
  description: Safari
  onfalse:
    - type: logbook
      delay: 0
      interval: 0
      message: Cold
d25f8c914a65:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition:
    - type: mqtt
      trigger: 'no'
      topic: __REPLACE__
      operator: eq
      jmespath: val
      value: ''
  ontrue:
    - type: email
      delay: 0
      interval: 0
      to: __REPLACE__@mail.com
      subject: __REPLACE__
      body: ''
  onfalse:
    - type: webhook
      delay: 0
      interval: 0
      url: __REPLACE__
'78903448e823':
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
