TimeDateUpdate:
  name: TDU
  category: Stuff
  order: 0
  condition:
    - type: cron
      trigger: always
      'off': ''
      'on': 15 * * * *
  ontrue:
    - type: script
      script: 'write(''knx/write/15/1/0'', new Date().toString());'
    - type: script
      script: 'write(''knx/write/15/1/1'', new Date().toString());'
    - type: pushover
      delay: 0
      interval: 0
      title: __REPLACE__
      message: ''
      sound: pushover
      priority: 0
    - type: mqtt
      delay: 0
      interval: 0
      topic: __REPLACE__
      value: __REPLACE__
  pendingOption: never
  enabled: false
  description: The description asdfasdf
  itemName: a
  jos: TDU
Logbook:
  name: Logbook
  category: Stuff
  order: 1
  condition:
    - type: cron
      trigger: always
      'off': ''
      'on': '*/1 * * * *'
  ontrue:
    - type: logbook
      message: test to logbook123
  pendingOption: always
  enabled: false
DoorBell:
  name: Doorbell
  category: Other Stuff
  order: 0
  condition:
    - type: mqtt
      trigger: on_flip_true
      topic: knx/status/15/2/3
      jmespath: val
      value: '0x01'
    - type: and
      condition:
        - type: and
          condition:
            - type: or
              condition:
                - type: mqtt
                  trigger: 'no'
                  topic: __REPLACE__
                  operator: eq
                  jmespath: val
                  value: ''
            - type: or
              condition: []
    - type: mqtt
      trigger: 'no'
      topic: __REPLACE__
      operator: eq
      jmespath: val
      value: ''
    - type: or
      condition: []
    - type: mqtt
      trigger: 'no'
      topic: __REPLACE__
      operator: eq
      jmespath: val
      value: ''
    - type: and
      condition: []
    - type: and
      condition: []
    - type: mqtt
      trigger: 'no'
      topic: __REPLACE__
      operator: eq
      jmespath: val
      value: ''
    - type: or
      condition: []
    - type: and
      condition: []
    - type: and
      condition: []
    - type: mqtt
      trigger: 'no'
      topic: __REPLACE__
      operator: eq
      jmespath: val
      value: ''
    - type: mqtt
      trigger: 'no'
      topic: __REPLACE__
      operator: eq
      jmespath: val
      value: ''
    - type: cron
      trigger: 'no'
      'on': 0 0 * * *
      'off': '-'
    - type: alias
      trigger: 'no'
      alias: __REPLACE__
      eval: 'true'
    - type: mqtt
      trigger: 'no'
      topic: __REPLACE__
      operator: eq
      jmespath: val
      value: ''
    - type: cron
      trigger: 'no'
      'on': 0 0 * * *
      'off': '-'
    - type: or
      condition: []
    - type: or
      condition: []
    - type: and
      condition: []
  ontrue:
    - type: pushover
      message: Notification from script4mqtt
      title: Doorbell ringing!
      sound: bike
      priority: 1
    - type: mqtt
      delay: 0
      interval: 0
      topic: __REPLACE__
      value: __REPLACE__
    - type: email
      delay: 0
      interval: 0
      to: __REPLACE__
      subject: __REPLACE__
      body: ''
    - type: mqtt
      delay: 0
      interval: 0
      topic: __REPLACE__
      value: __REPLACE__
  pendingOption: always
  enabled: false
  description: deurbelAaassasasasdf
  onfalse:
    - type: pushover
      delay: 0
      interval: 0
      title: __REPLACE__
      message: ''
      sound: pushover
      priority: 0
ef2a1abf4e20:
  name: New rule
  category: default
  description: ''
  enabled: true
  condition: []
2bf3c2a03716:
  name: New rule
  category: default
  description: ''
  enabled: true
  condition: []
b59d44f48aac:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
76b2870b34bc:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
8c19de6b776a:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
674e5d85071b:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
f71ef89feb8a:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
f6469c4b2caf:
  name: New ruleasdf
  category: default
  description: ''
  enabled: false
  condition: []
a1b16944408a:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
0d17306e96b1:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
798e5dc407bd:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
651dec0c7e7f:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
c197db5ab8f5:
  name: New ruleasdf
  category: default
  description: ''
  enabled: false
  condition: []
3eb3a5e19983:
  name: New ruleasdf
  category: default
  description: ''
  enabled: false
  condition: []
607a6f14fcdc:
  name: New ruleasdfsadf
  category: default
  description: ''
  enabled: false
  condition: []
1c9f16102929:
  name: New ruleasdfsadfasdfasdf
  category: default
  description: ''
  enabled: false
  condition: []
afb5b726710a:
  name: New rule
  category: default
  description: ''
  enabled: false
  condition: []
